apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arabic-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:223258934743:certificate/280b9b33-fac3-4637-9751-26cbb0e4fa92
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  ingressClassName: alb
  rules:
    - host: arabicapp.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arabic-app-service
                port:
                  number: 80
